#!/bin/bash

set -euxo pipefail

# Version

VERSION=$(node -e "console.log(require('./package.json').version)")

cat << EOF > ./src/version.ts
// Generated by yarn build
export const VERSION = '${VERSION}';
EOF

# ESM

rm -rf ./lib
tsc --project ./tsconfig-build.json
