#!/bin/bash

set -euxo pipefail

# Version

VERSION=$(node -e "console.log(require('./package.json').version)")

cat << EOF > ./src/version.ts
// Generated by "pnpm build"
export const VERSION = '${VERSION}'; // x-release-please-version
EOF

# ESM

rm -rf ./lib
tsc --project ./tsconfig-build.json
