name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write # Required for OIDC npm publishing

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v5.0.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - if: ${{ needs.release.outputs.release_created }}
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ needs.release.outputs.tag_name }}
      - if: ${{ needs.release.outputs.release_created }}
        uses: pnpm/action-setup@v6.0.8
      - if: ${{ needs.release.outputs.release_created }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - if: ${{ needs.release.outputs.release_created }}
        run: pnpm install
      - if: ${{ needs.release.outputs.release_created }}
        run: npm publish
