name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node:
          - 22
          - 24
          - 25

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: pnpm/action-setup@v5.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:pretty
      - run: pnpm test
      - run: pnpm test:types
      - run: pnpm test:build
      - run: pnpm test:coverage
        if: matrix.node == 24
      - name: Upload coverage to Codecov
        if: matrix.node == 24
        uses: codecov/codecov-action@v6.0.0
        with:
          directory: ./coverage/
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
